server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sportsacademy
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
